//------------------------------------------------------------------------------
//	<auto-generated>
//		Changes to this file may cause a malfunction and will be lost in case
//		of re-code generation.
//	</auto-generated>
//------------------------------------------------------------------------------
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyCompany("PENTEGY SERVICES LLC")]
[assembly: System.Reflection.AssemblyConfiguration("Debug")]
[assembly: System.Reflection.AssemblyCopyright("© 2011-2018 PENTEGY SERVICES LLC. All rights reserved.")]
[assembly: System.Reflection.AssemblyCulture("")]
#if DelaySign
[assembly: System.Reflection.AssemblyDelaySign(true)]
#endif
[assembly: System.Reflection.AssemblyFileVersion("1.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersion("0.0.rs_main.180201-1300")]
#if DelaySign
[assembly: System.Reflection.AssemblyKeyFile(@"..\PentegyServices.Logging.OpenSource.snk")]
#endif
[assembly: System.Reflection.AssemblyProduct("Pentegy Services | Logging Framework®")]
[assembly: System.Reflection.AssemblyTrademark("Pentegy Services | Logging Framework® is a registered trademark of PENTEGY SERVICES LLC.")]
#if !XmlSerializers
[assembly: System.Reflection.AssemblyVersion("1.0.0.0")]
#endif
[assembly: System.Resources.NeutralResourcesLanguage("en", System.Resources.UltimateResourceFallbackLocation.Satellite)]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
